Update IdPs/SPs from SAML metadata
REANNZ/reporting-service pull request #2
Opened 2022-04-20 22:24 UTC by James-REANNZ

Some IdPs/SPs are added directly to the SAML service. The reporting service sources it's information from the federation registry, meaning it doesn't see those entities. This change pulls metadata from the SAML service to augment the data from the federation registry.

2022-05-10 03:44 UTC, vladimir-mencl-eresearch commented
Hi @James-REANNZ ,

Thanks for the PR and sorry about the long delay in getting back to you.  School holidays and then sick children got in the way.  (Plus when I saw you were already working out the thoughts for a replacement, I thought this might be low priority anyway....)

But here are my thoughts on the PR.

(1) I like how you approached this with parsing the metadata from the SAML service (and found code to reuse for dealing with the metadata parsing).

(2) I would like to see a clear position on what remains as the role of the original sync from the Federation Registry.  I see the `clean` method is modified to only purge attribute definitions that have not been seen by the sync.  But it appears it would still attempt to synchronise (copy in) everything it used to sync.

All IdPs and SPs seen in the FR would also be seen in SAML Service.  So it might be right to remove them from the scope of the sync.

A tricky bit is that Organizations would only be seen in the SAML Service metadata if they have at least one IdP or SP - while FR also exposes Organizations that are "empty shells".  But the only benefit of having these Organizations visible in the Reporting Service is for the report on Federation Growth (number of registrations) - which I do not see as this crucial.

Perhaps this is more a question for the new Proposal for Reporting Service replacement (whether to sync empty Organizations).

But my main point here is to see a clear position on how the new sync from SAML Service interacts with the existing sync from FR.

But, if the new proposal moves forward, all of this may be just academic discussion.

I have a bit more feedback on individual aspects and I'll try attaching that to specific lines in the code.

But this is the main summary: like the approach, but want to see the clear position on how the two mechanisms would interact.

And thanks for getting it into the PR!

Cheers,
Vlad

2022-05-10 03:56 UTC, vladimir-mencl-eresearch requested changes

2022-05-10 03:56 UTC, vladimir-mencl-eresearch commented on .rubocop.yml
> +    - app/jobs/update_from_saml_service.rb
In the AAF code base, I've generally seen per-class exclusions done inline, for from `.rubocop.yml`

2022-05-10 03:56 UTC, vladimir-mencl-eresearch commented on Gemfile.lock
> +  aaf-lipstick (>= 4.5.1)!
Why the exclamation mark at the end of the line?

2022-05-10 03:56 UTC, vladimir-mencl-eresearch commented on app/jobs/update_from_saml_service.rb
> +    digest = OpenSSL::Digest.new('SHA256').digest("tuakiri:subscriber:#{name}")
I'm a little concerned about having two `org_identifier` methods that provide the same function but implement it differently - potential source for confusion.
https://github.com/REANNZ/reporting-service/blob/master/app/jobs/concerns/query_federation_registry.rb#L13

2022-05-10 03:56 UTC, vladimir-mencl-eresearch commented on app/jobs/update_from_saml_service.rb
> +    name_node = xpath_at(node, './md:Extensions/mdui:UIInfo/mdui:DisplayName')
Watch out - there might be multiple instances of `mdui:DisplayName`, distinguished by the `xml:lang` attribute.  You'd want `xml:lang="en"`.  In Tuakiri, you'd likely only see the `en` versions, but eduGAIN-imported metadata might have more languages.

2022-05-10 03:56 UTC, vladimir-mencl-eresearch commented on app/jobs/update_from_saml_service.rb
> +    name_node = xpath_at(node, './md:Extensions/mdui:UIInfo/mdui:DisplayName')
Same comment - should expect multiple instances and pick the `en` version.

2022-05-10 03:56 UTC, vladimir-mencl-eresearch commented on app/jobs/update_from_saml_service.rb
> +    org_name_node = xpath_at(node, './md:OrganizationDisplayName')
Same comment - should expect multiple instances and pick the `en` version.

2022-05-10 03:56 UTC, vladimir-mencl-eresearch commented on config/reporting_service.yml.dist
> +  # metadata_cert: "The Certificate"
It wasn't clear to me right away whether this was meant to be a path to the certificate or the certificate embedded directly.  Probably obvious (and just not to me), but maybe the sample value could make it even clearer?

2022-05-10 03:56 UTC, vladimir-mencl-eresearch commented on db/migrate/20220413213421_add_domain_to_organisation.rb
> +class AddDomainToOrganisation < ActiveRecord::Migration[6.0]
I have seen AAF committing the magic string:
`# frozen_string_literal: true`
as the first line of all Ruby code, including migrations - I expect Rubocop will complain if it isn't there...

2022-05-10 03:58 UTC, vladimir-mencl-eresearch commented
Done with the review. Happy to discuss offline (Slack or Zoom) - though not sure how much this is worth pursuing - also depends on how the Reporting Service Replacement proposal progresses.

2024-05-06 04:02 UTC, vladimir-mencl-eresearch commented on db/migrate/20220413213421_add_domain_to_organisation.rb
> +class AddDomainToOrganisation < ActiveRecord::Migration[6.0]
No longer required by Rubocop.

2024-05-06 04:05 UTC, vladimir-mencl-eresearch commented on Gemfile.lock
> +  aaf-lipstick (>= 4.5.1)!
Got it in master in the meantime as well - I assume newer bundler syntax.

2024-05-06 04:07 UTC, vladimir-mencl-eresearch commented on .rubocop.yml
> +    - app/jobs/update_from_saml_service.rb
The `.rubocop.yml` file needs rebasing anyway, I'll change this in the rebase.

2024-05-06 21:14 UTC, vladimir-mencl-eresearch commented on config/reporting_service.yml.dist
> +  # metadata_cert: "The Certificate"
As  configuration is now via env vars, which is not exactly suitable for passing full certificates, I'll change the setting to use path to certificate instead.

2024-05-06 22:06 UTC, vladimir-mencl-eresearch commented on app/jobs/update_from_saml_service.rb
> +    name_node = xpath_at(node, './md:Extensions/mdui:UIInfo/mdui:DisplayName')
Sorted.

2024-05-06 22:06 UTC, vladimir-mencl-eresearch commented on app/jobs/update_from_saml_service.rb
> +    name_node = xpath_at(node, './md:Extensions/mdui:UIInfo/mdui:DisplayName')
Sorted

2024-05-06 22:06 UTC, vladimir-mencl-eresearch commented on app/jobs/update_from_saml_service.rb
> +    org_name_node = xpath_at(node, './md:OrganizationDisplayName')
Sorted

2024-05-06 23:27 UTC, vladimir-mencl-eresearch commented on app/jobs/update_from_saml_service.rb
> +    digest = OpenSSL::Digest.new('SHA256').digest("tuakiri:subscriber:#{name}")
Renamed to avoid confusion.

2024-05-06 23:51 UTC, vladimir-mencl-eresearch approved these changes

2024-05-07 21:29 UTC, James-REANNZ reviewed
Looks good to me (and not just because half of it is my work :P).

2024-05-07 21:29 UTC, James-REANNZ commented on app/jobs/update_from_saml_metadata.rb
> +    org_name_node = xpath_at(node, "./md:OrganizationDisplayName[@xml:lang='en']") ||
Do we want to handle the case where there isn't an english name, but there is a non-english name? Or is that not worth handling?

2024-05-07 22:35 UTC, vladimir-mencl-eresearch commented on app/jobs/update_from_saml_metadata.rb
> +    org_name_node = xpath_at(node, "./md:OrganizationDisplayName[@xml:lang='en']") ||
Thanks, good point.  I thought of it as an edge-case with a question mark.  But if it ever gets used to ingest eduGAIN metadata, anything should be expected - including no name at all.

Pushed now - thanks for the suggestion.

2024-05-07 22:54 UTC, merged